[package]
name = "bgci-ratings"
version = "0.1.0"
edition = "2024"
default-run = "bgci-ratings"

[[bin]]
name = "bgci-ratings"
path = "src/main.rs"

[dependencies]
bgci-core = { path = "../bgci-core" }
clap = { version = "4.5", features = ["derive"] }
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
